name: GitHub Actions Build

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:
    inputs:
      release:
        description: "Create a release"
        type: choice
        required: false
        default: 'false'
        options:
          - 'true'
          - 'false'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@main

    - name: Auto Increment Version
      if: ${{ inputs.release == 'true' }}
      uses: MCKanpolat/auto-semver-action@v1
      id: versioning
      with:
        releaseType: minor 
        incrementPerCommit: false
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure build
      run: ./premake5 vs2022 --with-version=${{ steps.versioning.outputs.version }}

    - name: Build
      run: |
        msbuild -m build/MaxPayne3.FusionFix.sln /property:Configuration=Release /property:Platform=Win32

    - name: Download Ultimate ASI Loader x86
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "ThirteenAG/Ultimate-ASI-Loader"
        tag: "Win32-latest"
        fileName: "dinput8-Win32.zip"

    - name: Unpack dependencies
      run: |
          7z x dinput8-Win32.zip -odata/ -y
          del dinput8-Win32.zip

    - name: Pack binaries
      run: |
        ./release.bat

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MaxPayne3.FusionFix
        path: ./*

    - name: Upload Release (Main)
      if: |
        github.ref_name == 'master' &&
        (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
        github.repository == 'ThirteenAG/Ultimate-ASI-Loader'
      uses: ncipollo/release-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: false
        name: MaxPayne3.FusionFix v${{ steps.versioning.outputs.version }}
        bodyFile: "release.md"
        tag: v${{ steps.versioning.outputs.version }}
        artifacts: bin/MaxPayne3.FusionFix.zip

